apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: observability
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels: { app: loki }
  template:
    metadata:
      labels: { app: loki }
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.5
          args: ["-config.file=/etc/loki/config.yaml"]
          volumeMounts:
            - name: config
              mountPath: /etc/loki
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: observability
data:
  config.yaml: |
    server:
      http_listen_port: 3100
    auth_enabled: false
    common:
      path_prefix: /tmp/loki
    schema_config:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    compactor:
      working_directory: /tmp/loki/compactor
