apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kafka-lag-rules
  namespace: observability
spec:
  groups:
    - name: kafka
      rules:
        - record: kafka:consumer_lag
          expr: max(kafka_consumergroup_lag) by (topic,group)
        - record: kafka:lag_p95
          expr: histogram_quantile(0.95, sum by (le) (rate(kafka_consumergroup_lag_bucket[5m])))
