# observability-stack/prometheus/rules/wallet-queue-rules.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: wallet-queue-rules
  namespace: observability
spec:
  groups:
    - name: wallet
      rules:
        - record: wallet:withdraw_queue_time_s:p95
          expr: histogram_quantile(0.95, sum by (le) (rate(wallet_withdraw_queue_time_seconds_bucket[5m])))
        - record: wallet:queue_depth
          expr: max(wallet_withdraw_queue_depth) by (chain)
