apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: dr-alerts
  namespace: observability
spec:
  groups:
    - name: dr-alerts
      rules:
        - alert: RegionFailoverTimeExceeded
          expr: max(rpo_rto_seconds) > 600
          for: 5m
          labels:
            severity: critical
            owner: sre
          annotations:
            summary: "failover duration 넘친다 애들아"
